version: '3.1'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    networks:
      dh-bridge:
        ipv4_address: 172.29.0.10
networks:
  dh-bridge:
    external: true
