version: '3'

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    # ports:
    #   - '8016:80'
    restart: unless-stopped
    volumes:
      - ./bw-data/:/data/
    environment:
      - 'SIGNUPS_ALLOWED=false'

    networks:
      dh-bridge:
        ipv4_address: 172.29.0.25
networks:
  dh-bridge:
    external: true
volumes:
  data:
