version: "3.5"
services:
  languagetool:
    container_name: languagetool
    image: silviof/docker-languagetool:latest
    # ports:
    #   - "8010:8010"
    restart: unless-stopped
    networks:
      dh-bridge:
        ipv4_address: 172.29.0.45

networks:
  dh-bridge:
    external: true
