version: '3'
services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    ports:
      - "3015:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
      - "yacht:/config"
    networks:
      dh-bridge:
        ipv4_address: 172.29.0.85

networks:
  dh-bridge:
    external: true

volumes:
  yacht:
