version: '3.7'

services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'localhost:10080'
    ports:
      - '10080:80'
      - '10022:22'
    networks:
      - system
    volumes:
      - '../volumes/gitlab/config:/etc/gitlab'
      - '../volumes/gitlab/logs:/var/log/gitlab'
      - '../volumes/gitlab\data:/var/opt/gitlab'
    environment:
      - GITLAB_HOST=localhost
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_ROOT_PASSWORD=dom53361

#docker exec -it gitlab-ce grep 'Password:' /etc/gitlab/initial_root_password