version: '3.7'

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    restart: unless-stopped
    volumes:
      - ../volumes/bitwarden/data:/data/
    environment:
      - 'SIGNUPS_ALLOWED=false'

    networks:
      tools:
        ipv4_address: 172.29.0.25

networks:
  tools:
    external: true

volumes:
  data:
