version: "3.7"

services:
  dashy:
    container_name: dashy
    volumes:
      - ../volumes/conf.yml:/app/public/conf.yml
    image: lissy93/dashy:latest
    ports:
     - "4000:80"
    restart: unless-stopped
    networks:
      tools:
        ipv4_address: 172.29.0.65

networks:
  tools:
    external: true
