version: "3.7"

services:
  librespeed:
    container_name: "librespeed"
    entrypoint:
      - "/init"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "TZ=Europe/London"
    hostname: "d2f06f95a172"
    image: "lscr.io/linuxserver/librespeed:latest"
    ipc: "private"
    labels:
      build_version: "Linuxserver.io version:- 5.2.5-ls129 Build-date:- 2023-02-14T05:57:18+01:00"
      local.yacht.port.8008: "WebUI"
      maintainer: "aptalca"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-02-14T05:57:18+01:00"
      org.opencontainers.image.description: "[Librespeed](https://github.com/librespeed/speedtest)\
        \ is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest\
        \ and Web Workers.    No Flash, No Java, No Websocket, No Bullshit.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-librespeed"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "25ea517aecf012425ad0a73b28480aab69b11546"
      org.opencontainers.image.revision: "25ea517aecf012425ad0a73b28480aab69b11546"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-librespeed"
      org.opencontainers.image.title: "Librespeed"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-librespeed/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "5.2.5-ls129"
    logging:
      driver: "json-file"
      options: { }
    mac_address: "02:42:ac:11:00:02"
    network_mode: "bridge"
    ports:
      - "8008:80/tcp"
    restart: "unless-stopped"
    volumes:
      - "../volumes/librespeed/config:/config"
    working_dir: "/"
    networks:
      tools:
        ipv4_address: 172.29.0.45

networks:
  tools:
    external: true