version: '3.7'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ../volumes/bw-data/:/data/
    environment:
      - 'SIGNUPS_ALLOWED=false'

    networks:
      tools:
        ipv4_address: 172.29.0.25

networks:
  tools:
    external: true

volumes:
  data:
