version: '3.7'

services:
  nginx-server:
    depends_on:
      - phpfpm
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - '8009:80'
    volumes:
      - ../volumes/nginx:/etc/nginx
      - ../volumes/html:/usr/share/nginx/html
    networks:
      web:
        ipv4_address: 172.29.0.4

  phpfpm:
    container_name: php-fpm
    restart: unless-stopped
    image: php:7.3-fpm
    volumes:
      - ../volumes/html:/usr/share/nginx/html
    networks:
      web:
        ipv4_address: 172.29.0.5

networks:
  web:
    external: true

volumes:
  nginx:
