version: '3.7'

services:
  wordpress:
    external_links:
      - wp-mysql
    container_name: wp-dominikhaid
    image: wordpress:latest
    ports:
      - '8024:80'
    restart: unless-stopped
    volumes: [ '../volumes/wordpress/:/var/www/html/wordpress' ]
    environment:
      WORDPRESS_DB_HOST: wp-mysql:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpass
      WORDPRESS_DB_NAME: wordpress
    networks:
      web:
        ipv4_address: 172.29.0.32

  wp-mysql:
    container_name: wp-mysql
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    networks:
      db:
        ipv4_address: 172.29.0.33

  wp-mysqladmin:
    container_name: wp-mysqladmin
    depends_on:
      - wp-mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - '8025:80'
    environment:
      PMA_HOST: wp-mysql:3306
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      db:
        ipv4_address: 172.29.0.34

networks:
  db:
    external: true

volumes:
  data:
