version: '3.7'

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    command: [ 'redis-server', '--appendonly', 'yes' ]
    hostname: redis
    networks:
      db:
        ipv4_address: 172.29.0.30
    volumes:
      - redis-data:/data

  redis-commander:
    container_name: redis-commander
    restart: unless-stopped
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8023:8081'
    networks:
      db:
        ipv4_address: 172.29.0.31

networks:
  db:
    external: true

volumes:
  redis-data:
